version: '3.8'
services:
  postgres:
    image: postgres:15  
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  
      POSTGRES_DB: forum_logs
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped